# Change these first
owner: guwalanipooja # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: guwalanipooja

sites:
  - name: Neosisly Production
    url: https://mindfool.in/up

status-website:
  # Since you are using guwalanipooja/upptime, you MUST uncomment baseUrl
  baseUrl: /upptime
  name: Neosisly Status
  introTitle: "Neosisly Uptime Monitor"
  introMessage: "Real-time monitoring for the Neosisly Rails 8 production environment."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/guwalanipooja/upptime

# This ensures the bot can open issues if the site goes down
# assignees:
#   - guwalanipooja
